server {
    listen 80;
    server_name ipbelkin.ru www.ipbelkin.ru;

    # Перенаправление всех HTTP-запросов на HTTPS
    return 301 https://ipbelkin.ru$request_uri;
}

server {
    listen 443 ssl;
    server_name ipbelkin.ru www.ipbelkin.ru;

    root /usr/share/nginx/html;
    index index.html;

    ssl_certificate     /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    # Основной блок для Vue SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Кэширование статики
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?|ttf)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }
}
